[package]
name = "flyio-dist"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
glob = "0.3"
log = "0.4"
simplelog = "0.12"